{"name": "test_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'h5' in 'this'", "trace": "self = <pytestDemo.test_class1.TestClass object at 0x10c170c88>\n\n    def test_one(self):\n        x = \"this\"\n>       assert \"h5\" in x\nE       AssertionError: assert 'h5' in 'this'\n\ntest_class1.py:39: AssertionError"}, "attachments": [{"name": "log", "source": "d8d8d5b9-7f37-439c-b201-08a08aec211b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c27a4c44-ba20-42a4-bd4b-b572db81a948-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "82992df2-bf16-4c26-86dc-879dc73330b5-attachment.txt", "type": "text/plain"}], "start": 1557831266390, "stop": 1557831266390, "uuid": "033ec59b-2b02-45eb-b9e1-c5c606a9c3d4", "historyId": "4483c5051c47c6a9a5319370e5421e16", "fullName": "test_class1.TestClass#test_one", "labels": [{"name": "suite", "value": "test_class1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "123deMacBook-Pro.local"}, {"name": "thread", "value": "50544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class1"}]}